### ISSUE TITLE
Heading reversed

### ISSUE THREAD

**Issue by zekhoi** [zakiego/zakiego-v3#4]
![image](https://user-images.githubusercontent.com/55708473/162582153-c53b4b75-9507-4e7e-86a8-e6ec7ad12fcb.png)
![image](https://user-images.githubusercontent.com/55708473/162582602-ac16eeee-059c-4a5c-841c-ffdef682cacd.png)

Ketika menggunakan fitur search di page "What I Read Today" sepertinya posisi Heading (All Articles) saat article Not Found tertukar dengan text "No posts found"-nya (berdasarkan page blog saat not found).

**Comment by zakiego** [comment]
Thank you Pak @zekhoi!

Penyakit laten saya kurang teliti

**Comment by zakiego** [comment]
Btw webnya sedang saya turunkan (https://twitter.com/zakiego/status/1512917366384230401), karena ada kesalahan, jadi penggunaan jadi melebihi limit :))
